export const PROMPTS = [
    {
        id: 1,
        name: 'Starter Format',
        tier: 'Tier 1',
        price: 0,
        priceLabel: 'FREE',
        icon: '🌱',
        description: 'The foundation prompt for simple apps and quick prototypes. Perfect for beginners.',
        features: ['Instant access', 'Copy-to-clipboard'],
        popular: false,
        unlockType: 'free' as const,
    },
    {
        id: 2,
        name: 'Pro Builder Format',
        tier: 'Tier 2',
        price: 0,
        priceLabel: 'FREE',
        icon: '⚡',
        description: 'Advanced structure with shortcuts for LLM, JSON, and RAG configurations.',
        features: ['LLM shortcuts', 'JSON templates', 'Instant Access'],
        popular: false,
        unlockType: 'form' as const,
    },
    {
        id: 3,
        name: 'Industry Engineer Format',
        tier: 'Tier 3',
        price: 3,
        priceLabel: '$3 or Referral',
        icon: '🏭',
        description: 'Production-grade prompt for enterprise-level applications.',
        features: ['Enterprise-ready', '3-level referral unlock'],
        popular: true,
        unlockType: 'referral' as const,
    },
    {
        id: 4,
        name: 'Universal Architecture',
        tier: 'Tier 4',
        price: 4.30,
        priceLabel: '$4.30',
        icon: '🌐',
        description: 'Multi-platform prompt that works across web, mobile, and desktop.',
        features: ['Cross-platform', 'Architecture docs'],
        popular: false,
        unlockType: 'paid' as const,
    },
    {
        id: 5,
        name: 'Ultimate A→Z Blueprint',
        tier: 'Tier 5',
        price: 6.90,
        priceLabel: '$6.90',
        icon: '🗺️',
        description: 'Complete end-to-end application blueprint from idea to deployment.',
        features: ['Full roadmap', 'Deployment guide'],
        popular: false,
        unlockType: 'paid' as const,
    },
    {
        id: 6,
        name: 'Master Super Pack',
        tier: 'Master Tier',
        price: 12,
        priceLabel: '$12',
        icon: '💎',
        description: 'All prompts in one bundle. Includes Markdown, JSON & TOML formats.',
        features: ['All formats included', 'Future updates', 'Priority support'],
        popular: false,
        isMaster: true,
        unlockType: 'paid' as const,
    },
    {
        id: 7,
        name: 'Debug & Optimize',
        tier: 'Tier 7',
        price: 4,
        priceLabel: 'Coming Soon',
        icon: '🔧',
        description: 'Specialized prompt for debugging and optimizing AI-generated code.',
        features: ['Error fixing', 'Performance tips'],
        popular: false,
        unlockType: 'coming-soon' as const,
    },
    {
        id: 8,
        name: 'UI/UX Designer',
        tier: 'Tier 8',
        price: 5,
        priceLabel: 'Coming Soon',
        icon: '◼️',
        description: 'Create stunning, modern interfaces with this design-focused prompt.',
        features: ['Modern aesthetics', 'Responsive design'],
        popular: false,
        unlockType: 'coming-soon' as const,
    },
    {
        id: 9,
        name: 'Launch & Scale',
        tier: 'Tier 9',
        price: 5,
        priceLabel: 'Coming Soon',
        icon: '📈',
        description: 'Final prompt for deployment, scaling, and production optimization.',
        features: ['Hosting guides', 'Scaling strategies'],
        popular: false,
        unlockType: 'coming-soon' as const,
    },
]

export const FAQ_ITEMS = [
    {
        q: 'What exactly do I get after unlocking?',
        a: 'Instant access to the prompt text. You\'ll see the full prompt with a copy-to-clipboard button. Use it unlimited times with ChatGPT, Claude, or any AI.',
    },
    {
        q: 'How does the referral unlock work?',
        a: 'For Tier 3, you can either pay $3 OR invite people using your referral link. When 3 people you invited also get 3 people each (9 total through your chain), Tier 3 unlocks for free!',
    },
    {
        q: 'Which AI does this work with?',
        a: 'All major AI models: ChatGPT (GPT-4), Claude, Gemini, and any other LLM. The prompts are engineered to work universally.',
    },
    {
        q: 'When will the other prompts be available?',
        a: 'Tiers 4-9 and the Master Pack are coming soon! Join the waitlist to be notified when they launch.',
    },
    {
        q: 'Do I need coding experience?',
        a: 'No! The prompts are designed so that the AI does the coding. You just describe what you want.',
    },
]
