// src/config/constants.ts - INR Pricing, Only Prompts 1-6

export const PROMPTS = [
    {
        id: 1,
        name: 'Starter Format',
        tier: 'Tier 1',
        price: 0,
        priceLabel: 'FREE',
        icon: '🌱',
        description: 'The foundation prompt for simple apps and quick prototypes. Perfect for beginners.',
        features: ['Instant access', 'No email required'],
        popular: false,
        unlockType: 'free' as const,
    },
    {
        id: 2,
        name: 'Pro Builder Format',
        tier: 'Tier 2',
        price: 0,
        priceLabel: 'FREE',
        icon: '⚡',
        description: 'Advanced structure with shortcuts for LLM, JSON, and RAG configurations.',
        features: ['Instant access', 'No email required'],
        popular: false,
        unlockType: 'form' as const,
    },
    {
        id: 3,
        name: 'Industry Engineer Format',
        tier: 'Tier 3',
        price: 29,
        priceLabel: '₹29',
        icon: '🏭',
        description: 'Production-grade prompt for enterprise-level applications.',
        features: ['Enterprise-ready', 'UPI/Card payment'],
        popular: true,
        unlockType: 'paid' as const,
    },
    {
        id: 4,
        name: 'Universal Architecture',
        tier: 'Tier 4',
        price: 49,
        priceLabel: '₹49',
        icon: '🌐',
        description: 'Multi-platform prompt that works across web, mobile, and desktop.',
        features: ['Cross-platform', 'Architecture docs'],
        popular: false,
        unlockType: 'paid' as const,
    },
    {
        id: 5,
        name: 'Ultimate A→Z Blueprint',
        tier: 'Tier 5',
        price: 69,
        priceLabel: '₹69',
        icon: '🗺️',
        description: 'Complete end-to-end application blueprint from idea to deployment.',
        features: ['Full roadmap', 'Deployment guide'],
        popular: false,
        unlockType: 'paid' as const,
    },
    {
        id: 6,
        name: 'Master Super Pack',
        tier: 'Master Tier',
        price: 99,
        priceLabel: '₹99',
        icon: '💎',
        description: 'All prompts in one bundle. Includes Markdown, JSON & TOML formats.',
        features: ['All formats', '4 variations', 'Best value'],
        popular: false,
        isMaster: true,
        unlockType: 'paid' as const,
    }
]

export const FAQ_ITEMS = [
    {
        q: 'What exactly do I get after unlocking?',
        a: 'Instant access to the prompt text. You can copy it to your clipboard or download it. Use it unlimited times with ChatGPT, Claude, or any AI.',
    },
    {
        q: 'Which AI does this work with?',
        a: 'All major AI models: ChatGPT (GPT-4), Claude, Gemini, and any other LLM. The prompts are engineered to work universally.',
    },
    {
        q: 'What payment methods do you accept?',
        a: 'We support UPI (PhonePe, Paytm, GPay), Debit/Credit Cards (Visa, Mastercard, RuPay), and Net Banking - all through secure Razorpay payment gateway.',
    },
    {
        q: 'Do I need coding experience?',
        a: 'No! The prompts are designed so that the AI does the coding. You just describe what you want.',
    },
    {
        q: 'Can I use these prompts commercially?',
        a: 'Yes! Once you purchase, you can use the prompts to build and sell your own apps.',
    },
]
